name: 'GCP Authentication'
description: 'Authenticate with Google Cloud Platform and set up service account'
inputs:
  gcp_credentials:
    description: 'GCP credentials JSON'
    required: true
  service_account:
    description: 'Service account email'
    required: true
  credentials_file_path:
    description: 'Path to store the Google Application Credentials file'
    required: false
    default: 'tmp/gcloud_credentials.json'
  google_application_credentials_path:
    description: 'Path to the Google Application Credentials file'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gcp_credentials }}

    - name: Set active service account
      shell: bash
      run: |
        gcloud auth activate-service-account ${{ inputs.service_account }} \
          --key-file=${{ inputs.google_application_credentials_path }}

    - name: Verify gcloud authentication and setup credentials file
      shell: bash
      run: |
        gcloud config set account ${{ inputs.service_account }}
        gcloud auth list
        gcloud config list

        echo "GCLOUD_CREDENTIALS_FILE_PATH=${{ inputs.credentials_file_path }}" >> $GITHUB_ENV

        mkdir -p $(dirname "${{ inputs.credentials_file_path }}")
        cp ${{ inputs.google_application_credentials_path }} ${{ inputs.credentials_file_path }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
